export const metadata = {
  title: "test list",
  description: "Generated by create next app",
};
export default function PhotoFeedLayout({ children,modal }) {
    return (
        <div>
          {children}
          {modal}
        </div>
    );
  }